<a href="https://colab.research.google.com/github/Rayhan212k/Exam-1/blob/main/Exam_1_(Handle_missing_value).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: Python's numerical computing library for efficient array operations and math functions.

Pandas: Python library for easy data manipulation and analysis using Series and DataFrames.

In [ ]:
import numpy as np
import pandas as pd

The data from the CSV file is loaded into a Pandas DataFrame named "df."

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Machine learning/Lab1 exam/exam.csv')
df

,Customer ID,Age,Gender,Product Category,Purchase Amount,Payment Method,Feedback,Loyalty Points,Membership Level
0,101,35.0,Male,Electronics,500.0,Credit Card,Great service!,100.0,Gold
1,102,28.0,Female,Clothing,600.0,Cash,NaN,50.0,NaN
2,103,NaN,Female,Food,300.0,Online Payment,Not satisfied,NaN,Bronze
3,104,42.0,Male,Beauty,NaN,NaN,Product arrived late,80.0,NaN
4,105,31.0,Other,Electronics,800.0,Cash,NaN,NaN,Bronze
5,106,45.0,Male,NaN,450.0,NaN,Excellent experience,150.0,Gold
6,107,38.0,Female,Clothing,NaN,Credit Card,NaN,70.0,NaN
7,108,29.0,NaN,Beauty,350.0,Online Payment,Poor customer service,90.0,Bronze
8,109,NaN,Male,Food,600.0,NaN,NaN,120.0,Gold
9,110,27.0,Female,NaN,550.0,Cash,NaN,110.0,Gold

Checks and shows how many missing values are in each column.

In [ ]:
df.isnull().sum()

Customer ID         0
Age                 2
Gender              1
Product Category    2
Purchase Amount     2
Payment Method      3
Feedback            5
Loyalty Points      2
Membership Level    3
dtype: int64

In [ ]:
#varM= df['Gender'].mode()[0]
#varM

In [ ]:
#df.Gender= df.Gender.fillna("varM")
#df

In [ ]:
#best hocche median use kora for outlare thakle

Fill the missing values in specific numeric columns ("Age", "Purchase Amount", and "Loyalty Points") of the DataFrame "df".

It replaces the missing values with the median value of each respective column.

In [ ]:
numeric_columns = ["Age", "Purchase Amount", "Loyalty Points"]
for col in numeric_columns:
    df[col].fillna(df[col].median(), inplace=True)
df

,Customer ID,Age,Gender,Product Category,Purchase Amount,Payment Method,Feedback,Loyalty Points,Membership Level
0,101,35.000,Male,Electronics,500.00,Credit Card,Great service!,100.00,Gold
1,102,28.000,Female,Clothing,600.00,Cash,NaN,50.00,NaN
2,103,34.375,Female,Food,300.00,Online Payment,Not satisfied,96.25,Bronze
3,104,42.000,Male,Beauty,518.75,NaN,Product arrived late,80.00,NaN
4,105,31.000,Other,Electronics,800.00,Cash,NaN,96.25,Bronze
5,106,45.000,Male,NaN,450.00,NaN,Excellent experience,150.00,Gold
6,107,38.000,Female,Clothing,518.75,Credit Card,NaN,70.00,NaN
7,108,29.000,NaN,Beauty,350.00,Online Payment,Poor customer service,90.00,Bronze
8,109,34.375,Male,Food,600.00,NaN,NaN,120.00,Gold
9,110,27.000,Female,NaN,550.00,Cash,NaN,110.00,Gold

Handles missing values in specific categorical columns ("Gender", "Product Category", "Payment Method", and "Membership Level") of the DataFrame "df".

It replaces the missing values with the mode (most frequent) value of each respective column.

In [ ]:
categorical_columns = ["Gender", "Product Category", "Payment Method", "Membership Level"]
for col in categorical_columns:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)
df

,Customer ID,Age,Gender,Product Category,Purchase Amount,Payment Method,Feedback,Loyalty Points,Membership Level
0,101,35.000,Male,Electronics,500.00,Credit Card,Great service!,100.00,Gold
1,102,28.000,Female,Clothing,600.00,Cash,NaN,50.00,Gold
2,103,34.375,Female,Food,300.00,Online Payment,Not satisfied,96.25,Bronze
3,104,42.000,Male,Beauty,518.75,Cash,Product arrived late,80.00,Gold
4,105,31.000,Other,Electronics,800.00,Cash,NaN,96.25,Bronze
5,106,45.000,Male,Beauty,450.00,Cash,Excellent experience,150.00,Gold
6,107,38.000,Female,Clothing,518.75,Credit Card,NaN,70.00,Gold
7,108,29.000,Female,Beauty,350.00,Online Payment,Poor customer service,90.00,Bronze
8,109,34.375,Male,Food,600.00,Cash,NaN,120.00,Gold
9,110,27.000,Female,Beauty,550.00,Cash,NaN,110.00,Gold

Replaces missing values in the "Feedback" column of the DataFrame "df" with the text "No feedback".

In [ ]:
df.Feedback= df.Feedback.fillna("No feedback")
df

,Customer ID,Age,Gender,Product Category,Purchase Amount,Payment Method,Feedback,Loyalty Points,Membership Level
0,101,35.000,Male,Electronics,500.00,Credit Card,Great service!,100.00,Gold
1,102,28.000,Female,Clothing,600.00,Cash,No feedback,50.00,Gold
2,103,34.375,Female,Food,300.00,Online Payment,Not satisfied,96.25,Bronze
3,104,42.000,Male,Beauty,518.75,Cash,Product arrived late,80.00,Gold
4,105,31.000,Other,Electronics,800.00,Cash,No feedback,96.25,Bronze
5,106,45.000,Male,Beauty,450.00,Cash,Excellent experience,150.00,Gold
6,107,38.000,Female,Clothing,518.75,Credit Card,No feedback,70.00,Gold
7,108,29.000,Female,Beauty,350.00,Online Payment,Poor customer service,90.00,Bronze
8,109,34.375,Male,Food,600.00,Cash,No feedback,120.00,Gold
9,110,27.000,Female,Beauty,550.00,Cash,No feedback,110.00,Gold

Again Checks and shows how many missing values are in each column.

In [ ]:
df.isnull().sum()

Customer ID         0
Age                 0
Gender              0
Product Category    0
Purchase Amount     0
Payment Method      0
Feedback            0
Loyalty Points      0
Membership Level    0
dtype: int64

Snippet imports necessary modules from the Scikit-learn library:

train_test_split: Used to split data into training and testing sets.

LabelEncoder: Used for encoding categorical labels into numerical values.

RandomForestClassifier: Implements a random forest classifier for machine learning tasks.

accuracy_score: Calculates the accuracy of a model's predictions.

confusion_matrix: Generates a confusion matrix to evaluate classification performance.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

Here the code prepares the data for modeling:

Selects specific columns ("Age", "Gender", "Purchase Amount", "Payment Method") from the DataFrame "df" as features (X).

The target variable "Membership Level" is assigned to "y".

The code uses the LabelEncoder to transform categorical variables ("Gender" and "Payment Method") into numerical representations.

The transformed values are then assigned back to the respective columns in the features DataFrame "X".

This encoding is crucial for machine learning algorithms to process categorical data effectively.

In [ ]:
X = df[["Age", "Gender", "Purchase Amount", "Payment Method"]]
y = df["Membership Level"]

label_encoder = LabelEncoder()
X["Gender"] = label_encoder.fit_transform(X["Gender"])
X["Payment Method"] = label_encoder.fit_transform(X["Payment Method"])

<ipython-input-82-a7fce3e79ec5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Gender"] = label_encoder.fit_transform(X["Gender"])
<ipython-input-82-a7fce3e79ec5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Payment Method"] = label_encoder.fit_transform(X["Payment Method"])

It divides the features DataFrame "X" and the target variable "y" into training and testing subsets.

The split is performed with a test size of 30% (0.3) of the data, while 70% is allocated for training.

The random_state parameter is set to 42 for reproducibility, ensuring the same split is achieved when the code is executed again.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
X_train

      Age  Gender  Purchase Amount  Payment Method
0  35.000       1           500.00               1
7  29.000       0           350.00               2
2  34.375       0           300.00               2
9  27.000       0           550.00               0
4  31.000       2           800.00               0
3  42.000       1           518.75               0
6  38.000       0           518.75               1

It initializes a Random Forest classifier model with a specific random state for reproducibility.

The Random Forest classifier is a machine learning algorithm that constructs an ensemble of decision trees for classification tasks.

The model is trained using the training feature data (X_train) and the corresponding target labels (y_train).

In [ ]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

The model's predictions for the testing feature data (X_test) are generated using the predict() method and stored in y_pred.

The accuracy of the model's predictions is calculated by comparing the predicted labels (y_pred) with the actual testing target labels (y_test) using the accuracy_score() function.

The confusion matrix is calculated using the confusion_matrix() function, specifically for the classes "Gold" and "Bronze" using the labels parameter.

In [ ]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred, labels=["Gold","Bronze"])

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 1.0
Confusion Matrix:
[[3 0]
 [0 0]]